### ISSUE TITLE
Pie charts overlapping

### ISSUE THREAD

**Issue by obrunodelgado** [MetalBlueberry/go-plotly#12]
Hello, 

First, thank you for your effort in creating a wrapper for Plotly. As a GO enthusiastic I think it's amazing to have such tool in Go ecosystem.

I saw that Fig.Data accepts an array Trace (or Traces), but I'm trying to plot two Pie Charts in the same Fig and they are overlapping. Is it possible to generate multiple charts in the same figure? 

This is my code:

```go
func generatePieOfNumberOfDiagnosedPeople(diagnosis *grob.Pie, womans *grob.Pie) {
	fig := &grob.Fig{}
	fig.Data = append(fig.Data, diagnosis, womans)
	fig.Layout = &grob.Layout{
		Title: &grob.LayoutTitle{
			Text: "Número de pessoas com possível diagnóstico de Síndrome do Impostor",
		},
	}

	offline.ToHtml(fig, "diagnosis.html")
}
```
This is the result:
![image](https://user-images.githubusercontent.com/2372140/230709116-357d6743-7e20-422f-92a8-aa07a443b738.png)

This is what I would like in the same HTML (ignore sizes):
![image](https://user-images.githubusercontent.com/2372140/230709207-5dedc463-8776-44b0-a713-59fe49146240.png)
![image](https://user-images.githubusercontent.com/2372140/230709275-3b8205f9-0d38-40d3-b083-6cd7f1d35089.png)

**Comment by mmichal9** [comment]
you are probably looking for something like this
<img width="799" alt="Screenshot 2023-04-17 at 23 05 23" src="https://user-images.githubusercontent.com/26767094/232610798-da9ebbf2-0249-4819-a946-842fce6f8ba5.png">

```

	d1 := grob.PieDomain{Row: 0, Column: 0}
	d2 := grob.PieDomain{Row: 1, Column: 0}
	d3 := grob.PieDomain{Row: 0, Column: 1}
	d4 := grob.PieDomain{Row: 1, Column: 1}

	fig := &grob.Fig{
		Data: grob.Traces{
			&grob.Pie{
				Type:   grob.TraceTypePie,
				Values: []int{1, 2, 3},
				Labels: []string{"one", "two", "three"},
				Domain: &d1,
				Name:   "d1",
			},
			&grob.Pie{
				Type:   grob.TraceTypePie,
				Values: []int{1, 2, 3},
				Labels: []string{"one", "two", "three"},
				Domain: &d2,
			},
			&grob.Pie{
				Type:   grob.TraceTypePie,
				Values: []int{1, 2, 3},
				Labels: []string{"one", "two", "three"},
				Domain: &d3,
			},
			&grob.Pie{
				Type:   grob.TraceTypePie,
				Values: []int{1, 2, 3},
				Labels: []string{"one", "two", "three"},
				Domain: &d4,
			},
		},
		Layout: &grob.Layout{
			Title: &grob.LayoutTitle{
				Text: "pie",
			},
			Grid: &grob.LayoutGrid{
				Rows:     2,
				Columns:  2,
				Roworder: grob.LayoutGridRoworderBottomToTop,
			},
		},
	}
```

**Comment by MetalBlueberry** [comment]
I assume this is resolved, Let me know if you have further questions

**Comment by obrunodelgado** [comment]
Thanks guys.
