### ISSUE TITLE
Support Two Y-Axes

### ISSUE THREAD

**Issue by FieldsYeh** [MetalBlueberry/go-plotly#13]
How to Support Two Y-Axes

**Comment by MetalBlueberry** [comment]
You can refer to Plotly.js documentation, the structures are exactly the same

https://plotly.com/javascript/multiple-axes/

The gist is that you need to define Yaxis2 variable in the Fig.Layout

**Comment by MetalBlueberry** [comment]
I'm going to close this for now, let me know if you have further questions
