### ISSUE TITLE
Way to render figure as static image (png, jpeg, svg)

### ISSUE THREAD

**Issue by stephane-seng** [MetalBlueberry/go-plotly#6]
Would it be difficult to render the figure to a static image like in the examples in https://plotly.com/python/renderers/

**Comment by MetalBlueberry** [comment]
Hi @stephane-seng

In the link you provided https://plotly.com/python/renderers/#static-image-renderers you can see that...

> A set of renderers is provided for displaying figures as static images. These renderers all rely on the orca static image export utility. See the Static Image Export page for more information on getting set up with [orca](https://github.com/plotly/orca).

So also the python implementation is using an external tool. You can refer to [orca](https://github.com/plotly/orca) documentation to find how to use it and a few examples.

BTW, I've also added a quick example to call orca inside a docker container. you can find it in the [examples folder](https://github.com/MetalBlueberry/go-plotly/tree/master/examples/static_image)

Thank you for using go-plotly!
